# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aksesoris',
            fields=[
                ('id_aksesoris', models.CharField(help_text='ID Aksesoris', max_length=10, primary_key=True, serialize=False)),
                ('nama_aksesoris', models.CharField(help_text='Nama Aksesoris', max_length=40)),
                ('satuan_barang', models.CharField(default='Pieces', help_text='Satuan Aksesoris', max_length=40)),
                ('warna', models.CharField(help_text='Warna', max_length=20)),
                ('stok_akhir', models.IntegerField(default=0, help_text='Stok Akhir')),
                ('harga_per_satuan', models.IntegerField(default=0, help_text='Harga/Meter')),
                ('keterangan', models.TextField(help_text='Keterangan', max_length=100, null=True)),
                ('last_update', models.DateField(help_text='Terakhir Di-update')),
            ],
            options={
                'ordering': ['nama_aksesoris'],
            },
        ),
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id_bahan', models.CharField(help_text='ID Bahan', max_length=10, primary_key=True, serialize=False)),
                ('nama_bahan', models.CharField(help_text='Nama Bahan', max_length=40)),
                ('satuan_barang', models.CharField(default='Meter', help_text='Satuan Bahan', max_length=40)),
                ('warna', models.CharField(help_text='Warna', max_length=20)),
                ('stok_akhir', models.IntegerField(default=0, help_text='Stok Akhir')),
                ('harga_per_meter', models.IntegerField(default=0, help_text='Harga/Meter')),
                ('keterangan', models.TextField(help_text='Keterangan', max_length=100, null=True)),
                ('last_update', models.DateField(help_text='Terakhir Di-update')),
            ],
            options={
                'ordering': ['nama_bahan'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('art', models.CharField(help_text='ART', max_length=10, primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(help_text='Nama Produk', max_length=40)),
                ('serial', models.CharField(help_text='Serial', max_length=40)),
                ('brand', models.CharField(default='Pineapple', help_text='Brand', max_length=40)),
                ('jenis_tas', models.CharField(default='Ransel', help_text='Jenis Tas', max_length=40)),
                ('keterangan', models.TextField(help_text='Keterangan', max_length=100, null=True)),
                ('contoh_tas', models.CharField(help_text='Contoh Tas', max_length=100)),
            ],
            options={
                'ordering': ['art'],
            },
        ),
    ]
