# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aksesoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aksesoris', models.CharField(help_text='Nama Aksesoris', max_length=40)),
                ('satuan_barang', models.CharField(default='Pieces', help_text='Satuan Aksesoris', max_length=40)),
                ('warna', models.CharField(help_text='Warna', max_length=20)),
                ('stok_akhir', models.IntegerField(default=0, help_text='Stok Akhir')),
                ('harga_per_satuan', models.IntegerField(default=0, help_text='Harga/Meter')),
                ('keterangan', models.TextField(help_text='Keterangan', max_length=100, null=True)),
                ('last_update', models.DateField(help_text='Terakhir Di-update')),
            ],
            options={
                'ordering': ['nama_aksesoris'],
            },
        ),
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(help_text='Nama Bahan', max_length=40)),
                ('satuan_barang', models.CharField(default='Meter', help_text='Satuan Bahan', max_length=40)),
                ('warna', models.CharField(help_text='Warna', max_length=20)),
                ('stok_akhir', models.IntegerField(default=0, help_text='Stok Akhir')),
                ('harga_per_meter', models.IntegerField(default=0, help_text='Harga/Meter')),
                ('keterangan', models.TextField(help_text='Keterangan', max_length=100, null=True)),
                ('last_update', models.DateField(help_text='Terakhir Di-update')),
            ],
            options={
                'ordering': ['nama_bahan'],
            },
        ),
        migrations.CreateModel(
            name='HistoriAksesoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(help_text='Tanggal')),
                ('nomor_bukti', models.CharField(help_text='Nomor Bukti', max_length=10)),
                ('masuk', models.IntegerField(default=0, help_text='Masuk')),
                ('keluar', models.IntegerField(default=0, help_text='Keluar')),
                ('id_aksesoris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Aksesoris')),
            ],
            options={
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='HistoriBahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(help_text='Tanggal')),
                ('nomor_bukti', models.CharField(help_text='Nomor Bukti', max_length=10)),
                ('masuk', models.IntegerField(default=0, help_text='Masuk')),
                ('keluar', models.IntegerField(default=0, help_text='Keluar')),
                ('id_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Bahan')),
            ],
            options={
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='KebutuhanAksesoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemakaian_di', models.TextField(help_text='Pemakaian di', max_length=100)),
                ('jumlah_per_lusin', models.IntegerField(help_text='Jumlah/Lusin')),
                ('x', models.IntegerField(default=1, help_text='Faktor Pengali(X)')),
                ('marker', models.FloatField(default=1, help_text='Marker')),
                ('lembar_bahan', models.IntegerField(default=12, help_text='Lembar Bahan')),
            ],
            options={
                'ordering': ['id_aksesoris'],
            },
        ),
        migrations.CreateModel(
            name='KebutuhanBahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemakaian_untuk', models.TextField(help_text='Pemakaian untuk', max_length=100)),
                ('jumlah_per_lusin', models.IntegerField(help_text='Jumlah/Lusin')),
                ('x', models.IntegerField(default=1, help_text='Faktor Pengali(X)')),
                ('marker', models.FloatField(default=1, help_text='Marker')),
                ('lembar_bahan', models.IntegerField(default=12, help_text='Lembar Bahan')),
            ],
            options={
                'ordering': ['id_bahan'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_po', models.IntegerField(default=0, help_text='Production Order Number')),
                ('cust', models.CharField(help_text='Cust', max_length=40)),
                ('tanggal', models.DateField(help_text='Tanggal')),
            ],
            options={
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(help_text='ART', max_length=10)),
                ('nama_produk', models.CharField(help_text='Nama Produk', max_length=40)),
                ('serial', models.CharField(help_text='Serial', max_length=40)),
                ('brand', models.CharField(default='Pineapple', help_text='Brand', max_length=40)),
                ('jenis_tas', models.CharField(default='Ransel', help_text='Jenis Tas', max_length=40)),
                ('keterangan', models.TextField(help_text='Keterangan', max_length=100, null=True)),
                ('contoh_tas', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['art'],
            },
        ),
        migrations.CreateModel(
            name='ProdukPesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(help_text='Qty')),
                ('delv', models.DateField(help_text='Delv')),
                ('ket', models.TextField(help_text='Ket', max_length=100)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Produk')),
                ('no_po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allInOne.ProductionOrder')),
            ],
            options={
                'ordering': ['delv'],
            },
        ),
        migrations.CreateModel(
            name='WIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_wip', models.IntegerField(help_text='Qty WIP')),
                ('delivery', models.DateField(help_text='Delivery')),
                ('acc', models.DateField(help_text='ACC', null=True)),
                ('cutt', models.DateField(help_text='CUTT', null=True)),
                ('log', models.DateField(help_text='LOG', null=True)),
                ('tanggal_kirim', models.DateField(help_text='Tanggal Kirim')),
                ('makloon', models.CharField(default='NN', help_text='Makloon', max_length=20)),
                ('sewing_setor', models.IntegerField(default=0, help_text='Sewing Setor')),
                ('wip_sewing', models.IntegerField(default=0, help_text='WIP sewing')),
                ('sisa', models.IntegerField(default=0, help_text='Sisa')),
                ('keterangan', models.TextField(help_text='Keterangan', max_length=100)),
                ('reps', models.IntegerField(default=0, help_text='Reps')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Produk')),
                ('no_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.ProductionOrder')),
            ],
            options={
                'ordering': ['tanggal_kirim'],
            },
        ),
        migrations.AddField(
            model_name='kebutuhanbahan',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Produk'),
        ),
        migrations.AddField(
            model_name='kebutuhanbahan',
            name='id_bahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Bahan'),
        ),
        migrations.AddField(
            model_name='kebutuhanaksesoris',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Produk'),
        ),
        migrations.AddField(
            model_name='kebutuhanaksesoris',
            name='id_aksesoris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Aksesoris'),
        ),
    ]
