# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allInOne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkpesanan',
            name='no_po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.ProductionOrder'),
        ),
    ]
