# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allInOne', '0002_historiaksesoris_historibahan_kebutuhanaksesoris_kebutuhanbahan_productionorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukPesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(help_text='Qty')),
                ('delv', models.DateField(help_text='Delv')),
                ('ket', models.TextField(help_text='Ket', max_length=100)),
                ('pola', models.CharField(help_text='Pola', max_length=10)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Produk')),
                ('no_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.ProductionOrder')),
            ],
            options={
                'ordering': ['delv'],
            },
        ),
        migrations.CreateModel(
            name='WIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_wip', models.IntegerField(help_text='Qty WIP')),
                ('delivery', models.DateField(help_text='Delivery')),
                ('ket', models.TextField(help_text='Ket', max_length=100)),
                ('status_wip', models.CharField(default='BHN', help_text='Status WIP', max_length=20)),
                ('tanggal_kirim', models.DateField(help_text='Tanggal Kirim')),
                ('makloon', models.CharField(default='NN', help_text='Makloon', max_length=20)),
                ('sewing_setor', models.IntegerField(default=0, help_text='Sewing Setor')),
                ('wip_sewing', models.IntegerField(default=0, help_text='WIP sewing')),
                ('sisa', models.IntegerField(default=0, help_text='Sisa')),
                ('keterangan', models.TextField(help_text='Keterangan', max_length=100)),
                ('reps', models.IntegerField(default=0, help_text='Reps')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.Produk')),
                ('no_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allInOne.ProductionOrder')),
            ],
            options={
                'ordering': ['tanggal_kirim'],
            },
        ),
    ]
