# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allInOne', '0003_produkpesanan_wip'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaksesoris',
            name='keluar',
            field=models.IntegerField(default=0, help_text='Keluar'),
        ),
        migrations.AddField(
            model_name='historiaksesoris',
            name='masuk',
            field=models.IntegerField(default=0, help_text='Masuk'),
        ),
        migrations.AddField(
            model_name='historibahan',
            name='keluar',
            field=models.IntegerField(default=0, help_text='Keluar'),
        ),
        migrations.AddField(
            model_name='historibahan',
            name='masuk',
            field=models.IntegerField(default=0, help_text='Masuk'),
        ),
    ]
